// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-IB0POwzBhaVzNhDnFG-JewzSm9qS3Es',
    appId: '1:662603140937:web:580c11d6c89f8b2f6a1498',
    messagingSenderId: '662603140937',
    projectId: 'safetrack-76a0c',
    authDomain: 'safetrack-76a0c.firebaseapp.com',
    storageBucket: 'safetrack-76a0c.firebasestorage.app',
    measurementId: 'G-T9PW7FPCZP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-IB0POwzBhaVzNhDnFG-JewzSm9qS3Es',
    appId: '1:662603140937:ios:2ae3f06d48f48b6a05560a',
    messagingSenderId: '662603140937',
    projectId: 'safetrack-76a0c',
    storageBucket: 'safetrack-76a0c.firebasestorage.app',
    iosBundleId: 'com.example.protectid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-IB0POwzBhaVzNhDnFG-JewzSm9qS3Es',
    appId: '1:662603140937:web:154a6cdd4eda66fd05560a',
    messagingSenderId: '662603140937',
    projectId: 'safetrack-76a0c',
    authDomain: 'safetrack-76a0c.firebaseapp.com',
    storageBucket: 'safetrack-76a0c.firebasestorage.app',
    measurementId: 'G-T9PW7FPCZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxE1-lPFOY8ugfYQB_CvUR7xtWWhZZRFY',
    appId: '1:662603140937:android:79b904026f21f7996a1498',
    messagingSenderId: '662603140937',
    projectId: 'safetrack-76a0c',
    storageBucket: 'safetrack-76a0c.firebasestorage.app',
    databaseURL: 'https://safetrack-76a0c-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

}