// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ_AH38nTzMKxUJ4n1Dm5JMduSfdvZJFU',
    appId: '1:843470926015:web:a5c0d8426ebd7a9c05560a',
    messagingSenderId: '843470926015',
    projectId: 'protectid-f04a3',
    authDomain: 'protectid-f04a3.firebaseapp.com',
    storageBucket: 'protectid-f04a3.firebasestorage.app',
    measurementId: 'G-CMZBJYQ9KW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2uLRqLVjQOmExq4cqbize6EEt93zzi8c',
    appId: '1:843470926015:ios:2ae3f06d48f48b6a05560a',
    messagingSenderId: '843470926015',
    projectId: 'protectid-f04a3',
    storageBucket: 'protectid-f04a3.firebasestorage.app',
    iosBundleId: 'com.example.protectid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ_AH38nTzMKxUJ4n1Dm5JMduSfdvZJFU',
    appId: '1:843470926015:web:154a6cdd4eda66fd05560a',
    messagingSenderId: '843470926015',
    projectId: 'protectid-f04a3',
    authDomain: 'protectid-f04a3.firebaseapp.com',
    storageBucket: 'protectid-f04a3.firebasestorage.app',
    measurementId: 'G-9ZPTRESP0C',
  );

}